### PR TITLE
setup: add WhiskyWine download/install diagnostics + copy workflow (Fixes #63)

### LINKED ISSUE #63: WhiskyWine download stuck (0 KB / 0 seconds remaining / hangs at 100%)
Refs #45

## Summary
WhiskyWine download/installation sometimes stalls indefinitely:
- stuck at **0 KB** (never starts)
- stuck at **0 seconds remaining** / **100%**
- downloads but install never completes

This blocks all bottle creation and first-time setup.

## Upstream references (examples)
- whisky-app/whisky#1020 (0 KB)
- whisky-app/whisky#1271 (0 seconds remaining)
- whisky-app/whisky#1278 (wine64 missing/detection mismatch)

## What we want
- Surface actionable error state (network / disk / permission / checksum / tarball layout)
- Provide bounded diagnostics to attach to issues (URL, bytes received, retry count, extracted validation results)
- Ensure the installer either completes or fails with a clear reason (no silent hang)

## Data to include in reports
- macOS version + hardware
- Whisky version
- Network environment (VPN/proxy/captive portal)
- Approx download time before it stalls
- Available disk space
- Logs from **Open Logs Folder** around the download attempt

## Repro
TBD: capture reliable repro once we have a few diagnostics-backed reports.

### PR DESCRIPTION
**Pull request by frankea**
Fixes #63
Refs #45

## Summary
Adds lightweight instrumentation + a bounded, copyable diagnostics report for the WhiskyWine download/install flow. This is aimed at making “stuck at 0 KB / 0 seconds remaining / 100%” reports actionable without guessing.

## Changes
- Adds a `WhiskyWineSetupDiagnostics` recorder shared across Setup stages
- Records version-plist fetch, resolved download URL, HTTP status codes, progress bytes, timestamps, disk space
- Adds **Copy Diagnostics** + **Open Logs Folder** actions on download failure
- Adds install-stage validation: if install completes but WhiskyWine is still not detected, show an error with copyable diagnostics and retry

## How to verify
- Force a failure (e.g. block network) and confirm Download view shows Copy Diagnostics and Open Logs
- Copy diagnostics and verify it includes stage, URLs, HTTP codes (when available), bytes, timestamps, disk space
- Corrupt/missing tarball path and confirm install stage surfaces failure via diagnostics instead of silently proceeding

## Review Checklist
- [ ] Diagnostics are bounded and do not include secrets
- [ ] Uses localization keys for new UI strings
- [ ] No regressions for successful setup path

### CODE REVIEW

**Comment by frankea** [comment]
Addressed the remaining PR 65 feedback in the latest push:

- Retry install now records retry start, validates `isWhiskyWineInstalled()`, and mirrors the 2s success checkmark delay before `proceed()`.
- `formatRemainingTime(...)` no longer double-checks `shouldShowEstimate()` (caller already guards).
- Removed the outer `_ =` around `MainActor.run { … }` in `FileOpenView` (kept inner discard so the closure returns `Void`).
- Added full localization coverage for `setup.whiskywine.copyDiagnostics` and `setup.whiskywine.error.installFailed`.
- PE nested types (`Magic`, `COFFFileHeader`, `Section`, `OptionalHeader`) remain in a `public extension PEFile`, which already makes them public by default; keeping explicit `public` triggers the Swift 6 redundant access modifier error. No API change.

Let me know if you want those threads marked resolved manually.

File: Whisky/Localizable.xcstrings [hunk 1]
```diff
@@ -17678,6 +17678,278 @@
         }
       }
     },
+    "setup.whiskywine.copyDiagnostics" : {
```
Comment (frankea) [inline Whisky/Localizable.xcstrings:17681]: Translations are managed via Crowdin in this repo. For new keys we intentionally land only the English base string; the translation pipeline will populate the other locales after merge. That’s why this section currently shows only `en`.

**Review by frankea — COMMENTED** [review]
Left an inline note on the localization workflow for the new WhiskyWine keys.

File: Whisky/Views/Setup/WhiskyWineInstallView.swift [hunk 2]
```diff
@@ -51,19 +58,107 @@ struct WhiskyWineInstallView: View {
...
+                )
+            }
+            .buttonStyle(.borderedProminent)
+            .disabled(installing)
+
+            Button("setup.quit") {
+                showSetup = false
+            }
+            .buttonStyle(.bordered)
+        }
```
Comment (frankea) [inline Whisky/Views/Setup/WhiskyWineInstallView.swift:132]: We already preserve prior attempt info before overwriting: `diagnostics.installStartedAt`/`installFinishedAt` are logged as "Previous install attempt …" and the event log appends rather than resets. That keeps retry history in the diagnostics even if a subsequent retry fails.
